---
- name: Set up host machine
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - role: fonts
      tags: fonts
    - role: utilities
      tags: utilities
    - role: nvim
      tags: nvim
    - role: zsh
      tags: zsh
    - role: bootstrap
      tags: bootstrap
