---

- name: Set up host machine
  hosts: vbox
  become: yes
  gather_facts: yes

  roles:
    - role: fonts
      tags: fonts
    - role: utilities
      tags: utilities
    - role: nvim 
      tags: nvim
    - role: zsh 
      tags: zsh
    - role: bootstrap
      tags: bootstrap
