---
roles:
  - name: geerlingguy.clamav
    src: git@github.com:geerlingguy/ansible-role-clamav.git
    scm: git

collections:
  - name: community.general
  - name: devsec.hardening
  - name: hifis.toolkit
