---
# ufw
- name: Install UFW with package manager
  become: true
  ansible.builtin.package:
    state: present
    name: ufw

- name: enable UFW
  community.general.ufw:
    state: enabled

- name: set logging
  community.general.ufw:
    logging: "on"

- name: allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"
    - "65522" #set up your own high SSH random port,
    - "22" # definitely remove that when above set up

- name: block ipv6
  community.general.ufw:
    rule: deny
    proto: ipv6
    direction: "{{ item }}"
  loop:
    - in
    - out
