- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Override powerline fonts package name for Debian.
  ansible.builtin.set_fact:
    powerlinefonts: fonts-powerline
  when: ansible_os_family == 'Debian'

- name: Install Powerline fonts
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ powerlinefonts }}"

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh-completions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1

- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: Install autoupdate-zsh-plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
    dest: ~/.oh-my-zsh/custom/plugins/autoupdate
    depth: 1

- name: Change user ({{ zsh_local_user }}) shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Tasks for p10k
  ansible.builtin.include_tasks: p10k.yml
