---
# Install eza (modern ls replacement)

- name: Install GPG and Wget prerequisites (Debian)
  become: true
  ansible.builtin.package:
    state: present
    name:
      - gpg
      - wget
  when: ansible_os_family == 'Debian'

- name: Download eza GPG key (Debian)
  become: true
  ansible.builtin.shell: >
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
  args:
    creates: /etc/apt/keyrings/gierens.gpg
  when: ansible_os_family == 'Debian'

- name: Set permissions on eza GPG key (Debian)
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/gierens.gpg
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Add eza repository (Debian)
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main"
    filename: gierens
    state: present
  when: ansible_os_family == 'Debian'

- name: Install eza
  become: true
  ansible.builtin.package:
    state: present
    name: eza
