---
- name: '[Dependencies] Install Dependencies for NerdFonts on Debian-based systems'
  apt:
    name:
    - fontconfig
    - git
    state: present
  register: nerdfonts_deps_install_result
  until: nerdfonts_deps_install_result is succeeded
  become: yes
  when: "'Debian' in ansible_os_family"
  tags:
  - nerdfonts
