---
- name: '[debian] Include Debian-specific variables'
  include_vars: debian.yml
  tags: nerdfonts

- name: '[debian] Setting nerdfonts_install_dir for system-wide installation'
  set_fact:
    nerdfonts_install_dir: "{{ nerdfonts_deb_fonts_sys_dir }}"
  when:
  - nerdfonts_deb_env is defined
  tags: nerdfonts

- name: '[debian] Create NerdFonts folder for system-wide installation'
  file:
    path: "{{ nerdfonts_install_dir }}/NerdFonts"
    state: directory
  when:
  - nerdfonts_deb_env is defined
  tags: nerdfonts

- name: '[debian] Create EnvyCodeR folder'
  file:
    path: "{{ nerdfonts_install_dir }}/NerdFonts/EnvyCodeR"
    state: directory
  when:
  - nerdfonts_deb_env is defined
  tags: nerdfonts

- name: '[debian] Download EnvyCodeNerdFont'
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/EnvyCodeR.zip
    dest: "{{ nerdfonts_install_dir }}/NerdFonts/EnvyCodeR"
    remote_src: yes
  when:
  - nerdfonts_deb_env is defined
  tags: nerdfonts

- name: '[debian] Update the Fonts Cache'
  command: "fc-cache -fv" 
  tags: nerdfonts
